# Generated by Django 4.2.17 on 2026-03-14 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Sana')),
                ('check_in', models.DateTimeField(blank=True, null=True, verbose_name='Kelish vaqti')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Ketish vaqti')),
                ('status', models.CharField(choices=[('present', 'Keldi'), ('late', 'Kech keldi'), ('absent', 'Kelmadi'), ('excused', 'Sababli kelmadi')], default='absent', max_length=20)),
                ('late_minutes', models.IntegerField(default=0, verbose_name='Kechikish (daqiqa)')),
                ('notes', models.TextField(blank=True, verbose_name='Izoh')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Davomad yozuvi',
                'verbose_name_plural': 'Davomad yozuvlari',
                'ordering': ['-date', 'student__last_name'],
            },
        ),
    ]
