# Generated by Django 4.2.17 on 2026-03-14 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('attendance', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancerecord',
            name='check_in_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkin_records', to='devices.device', verbose_name='Kelish qurilmasi'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='check_out_device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkout_records', to='devices.device', verbose_name='Ketish qurilmasi'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='raw_log',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='devices.devicerawlog'),
        ),
    ]
