# Generated by Django 4.2.17 on 2026-03-14 07:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Qurilma nomi')),
                ('brand', models.CharField(choices=[('hikvision', 'Hikvision'), ('dahua', 'Dahua'), ('zkteco', 'ZKTeco'), ('anviz', 'Anviz'), ('other', 'Boshqa')], max_length=20, verbose_name='Brend')),
                ('model', models.CharField(blank=True, max_length=100, verbose_name='Model')),
                ('serial_number', models.CharField(max_length=100, unique=True, verbose_name='Seriya raqami')),
                ('ip_address', models.GenericIPAddressField(verbose_name='IP manzil')),
                ('port', models.IntegerField(default=80, verbose_name='Port')),
                ('username', models.CharField(default='admin', max_length=50, verbose_name='Foydalanuvchi')),
                ('password', models.CharField(max_length=100, verbose_name='Parol')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='Joylashuv')),
                ('status', models.CharField(choices=[('online', 'Online'), ('offline', 'Offline'), ('syncing', 'Sinxronlanmoqda'), ('error', 'Xatolik'), ('unknown', "Noma'lum")], default='unknown', max_length=20)),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name="Oxirgi ko'rilgan")),
                ('firmware_version', models.CharField(blank=True, max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Qurilma',
                'verbose_name_plural': 'Qurilmalar',
                'ordering': ['school', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSyncLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sync_type', models.CharField(choices=[('push', 'Qurilmaga yuklash'), ('pull', 'Qurilmadan olish'), ('check', 'Holat tekshirish')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('running', 'Ishlayapti'), ('success', 'Muvaffaqiyatli'), ('failed', 'Muvaffaqiyatsiz')], default='pending', max_length=20)),
                ('total_records', models.IntegerField(default=0)),
                ('synced_records', models.IntegerField(default=0)),
                ('failed_records', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sync_logs', to='devices.device')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Sinxronizatsiya logi',
                'verbose_name_plural': 'Sinxronizatsiya loglari',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceRawLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_no', models.CharField(max_length=50, verbose_name='Xodim raqami (qurilmada)')),
                ('event_time', models.DateTimeField(verbose_name='Voqea vaqti')),
                ('event_type', models.IntegerField(default=0, verbose_name='Voqea turi')),
                ('temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('raw_data', models.JSONField(default=dict, verbose_name="Xom ma'lumot")),
                ('processed', models.BooleanField(default=False, verbose_name='Qayta ishlangan')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_logs', to='devices.device')),
            ],
            options={
                'verbose_name': 'Xom log',
                'verbose_name_plural': 'Xom loglar',
                'ordering': ['-event_time'],
            },
        ),
    ]
