# Generated by Django 4.2.17 on 2026-03-14 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='school',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='organizations.school'),
        ),
        migrations.AddIndex(
            model_name='devicerawlog',
            index=models.Index(fields=['device', 'event_time'], name='devices_dev_device__25082f_idx'),
        ),
        migrations.AddIndex(
            model_name='devicerawlog',
            index=models.Index(fields=['employee_no', 'event_time'], name='devices_dev_employe_c3717a_idx'),
        ),
        migrations.AddIndex(
            model_name='devicerawlog',
            index=models.Index(fields=['processed'], name='devices_dev_process_3d5fcf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='devicerawlog',
            unique_together={('device', 'employee_no', 'event_time')},
        ),
    ]
