# Generated by Django 4.2.17 on 2026-03-14 07:40

import apps.students.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('phone', models.CharField(max_length=15, unique=True, verbose_name='Telefon')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Telegram ID')),
                ('is_registered', models.BooleanField(default=False, verbose_name="Bot'ga ro'yxatdan o'tgan")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Ota-ona',
                'verbose_name_plural': 'Ota-onalar',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Otasining ismi')),
                ('phone', models.CharField(blank=True, max_length=15, verbose_name='Telefon')),
                ('subject', models.CharField(max_length=100, verbose_name='Fan')),
                ('employee_id', models.CharField(max_length=20, unique=True, verbose_name='Xodim ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.students.models.teacher_photo_path, verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='organizations.school')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': "O'qituvchi",
                'verbose_name_plural': "O'qituvchilar",
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100, verbose_name='Ism')),
                ('last_name', models.CharField(max_length=100, verbose_name='Familiya')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Otasining ismi')),
                ('birth_date', models.DateField(verbose_name="Tug'ilgan sana")),
                ('gender', models.CharField(choices=[('M', 'Erkak'), ('F', 'Ayol')], max_length=1, verbose_name='Jinsi')),
                ('student_id', models.CharField(max_length=20, unique=True, verbose_name="O'quvchi ID")),
                ('photo', models.ImageField(blank=True, null=True, upload_to=apps.students.models.student_photo_path, verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('class_ref', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='organizations.class', verbose_name='Sinf')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='organizations.school')),
            ],
            options={
                'verbose_name': "O'quvchi",
                'verbose_name_plural': "O'quvchilar",
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='ParentStudentLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_phone', models.CharField(max_length=15, verbose_name='Ota-ona telefoni')),
                ('relationship', models.CharField(choices=[('father', 'Ota'), ('mother', 'Ona'), ('guardian', 'Vasiy'), ('other', 'Boshqa')], default='father', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('active', 'Faol'), ('rejected', 'Rad etildi')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='student_links', to='students.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_links', to='students.student')),
            ],
            options={
                'verbose_name': "Ota-ona - O'quvchi bog'liq",
                'verbose_name_plural': "Ota-ona - O'quvchi bog'liqlari",
                'unique_together': {('student', 'parent_phone')},
            },
        ),
    ]
