# Generated by Django 4.2.17 on 2026-03-14 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classes', to='students.teacher', verbose_name='Sinf rahbari'),
        ),
        migrations.AlterUniqueTogether(
            name='district',
            unique_together={('region', 'code')},
        ),
        migrations.AlterUniqueTogether(
            name='class',
            unique_together={('school', 'grade', 'section', 'academic_year')},
        ),
    ]
