# Generated by Django 4.2.17 on 2026-03-14 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='district',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='Kod'),
        ),
        migrations.AlterField(
            model_name='region',
            name='code',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Kod'),
        ),
    ]
