# Generated by Django 4.2.17 on 2026-03-14 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_alter_district_code_alter_region_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='academic_year',
            field=models.CharField(default='2024-2025', max_length=10, verbose_name="O'quv yili"),
        ),
    ]
