# Generated by Django 4.2.17 on 2026-03-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_alter_class_academic_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='name',
            field=models.CharField(blank=True, max_length=20, verbose_name='Sinf nomi'),
        ),
    ]
